// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vkrxbvxitrgjixovhsww.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrcnhidnhpdHJnaml4b3Zoc3d3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MjIxNzcsImV4cCI6MjA2MzM5ODE3N30.XnqsVZg0nIUO4E9p_FwlDUXfz0gr5tXZcXQ0SQv2928";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);